github:
  description: "Apache OpenOffice Forums"
  homepage: https://forum.openoffice.org/
  features:
    issues: true
  labels:
    - apache
    - openoffice
    - forum
    - phpbb

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@openoffice.apache.org
  issues: dev@openoffice.apache.org
  pullrequests: dev@openoffice.apache.org
