github:
  description: "Apache OpenOffice.org Forums"
  homepage: https://forum.openoffice.org/
  labels:
    - apache
    - openoffice
    - forum
    
notifications:
  commits:      commits@openoffice.apache.org
  issues:       dev@openoffice.apache.org
  pullrequests: dev@openoffice.apache.org

